import { Fixture } from '@/types';

export const seedMatches: Fixture[] = [
  {
    id: 'm-1',
    competitionId: 'wc-2026',
    date: '2026-06-11T13:00:00Z',
    stadium: 'Estadio Azteca, Mexico City',
    homeTeam: {
      id: 'mex',
      name: 'Mexico',
      code: 'MEX',
      logo: 'https://flagcdn.com/w320/mx.png',
    },
    awayTeam: {
      id: 'fra',
      name: 'France',
      code: 'FRA',
      logo: 'https://flagcdn.com/w320/fr.png',
    },
    homeScore: null,
    awayScore: null,
    penalties: null,
  },
  {
    id: 'm-2',
    competitionId: 'wc-2026',
    date: '2026-06-12T18:00:00Z',
    stadium: 'SoFi Stadium, Los Angeles',
    homeTeam: { id: 'usa', name: 'USA', code: 'USA', logo: 'https://flagcdn.com/w320/us.png' },
    awayTeam: {
      id: 'ita',
      name: 'Italy',
      code: 'ITA',
      logo: 'https://flagcdn.com/w320/it.png',
    },
    homeScore: null,
    awayScore: null,
    penalties: null,
  },
  {
    id: 'm-3',
    competitionId: 'wc-2026',
    date: '2026-06-13T15:00:00Z',
    stadium: 'Hard Rock Stadium, Miami',
    homeTeam: {
      id: 'col',
      name: 'Colombia',
      code: 'COL',
      logo: 'https://flagcdn.com/w320/co.png',
    },
    awayTeam: {
      id: 'ger',
      name: 'Germany',
      code: 'GER',
      logo: 'https://flagcdn.com/w320/de.png',
    },
    homeScore: null,
    awayScore: null,
    penalties: null,
  },
  {
    id: 'm-4',
    competitionId: 'wc-2026',
    date: '2026-06-14T17:00:00Z',
    stadium: 'MetLife Stadium, New York',
    homeTeam: {
      id: 'bra',
      name: 'Brazil',
      code: 'BRA',
      logo: 'https://flagcdn.com/w320/br.png',
    },
    awayTeam: {
      id: 'uru',
      name: 'Uruguay',
      code: 'URU',
      logo: 'https://flagcdn.com/w320/uy.png',
    },
    homeScore: null,
    awayScore: null,
    penalties: null,
  },
  {
    id: 'm-5',
    competitionId: 'wc-2026',
    date: '2026-06-12T14:00:00Z',
    stadium: 'BMO Field, Toronto',
    homeTeam: {
      id: 'can',
      name: 'Canada',
      code: 'CAN',
      logo: 'https://flagcdn.com/w320/ca.png',
    },
    awayTeam: {
      id: 'eng',
      name: 'England',
      code: 'ENG',
      logo: 'https://flagcdn.com/w320/gb-eng.png',
    },
    homeScore: null,
    awayScore: null,
    penalties: null,
  },
  {
    id: 'm-6',
    competitionId: 'wc-2026',
    date: '2026-06-15T10:00:00Z',
    stadium: "Levi's Stadium, San Francisco",
    homeTeam: {
      id: 'esp',
      name: 'Spain',
      code: 'ESP',
      logo: 'https://flagcdn.com/w320/es.png',
    },
    awayTeam: {
      id: 'jpn',
      name: 'Japan',
      code: 'JPN',
      logo: 'https://flagcdn.com/w320/jp.png',
    },
    homeScore: null,
    awayScore: null,
    penalties: null,
  },
  {
    id: 'm-7',
    competitionId: 'wc-2026',
    date: '2026-06-16T16:00:00Z',
    stadium: 'AT&T Stadium, Dallas',
    homeTeam: {
      id: 'arg',
      name: 'Argentina',
      code: 'ARG',
      logo: 'https://flagcdn.com/w320/ar.png',
    },
    awayTeam: {
      id: 'por',
      name: 'Portugal',
      code: 'POR',
      logo: 'https://flagcdn.com/w320/pt.png',
    },
    homeScore: null,
    awayScore: null,
    penalties: null,
  },
  {
    id: 'm-8',
    competitionId: 'wc-2026',
    date: '2026-06-11T19:00:00Z', // Fecha cercana
    stadium: 'Mercedes-Benz Stadium, Atlanta',
    homeTeam: {
      id: 'bel',
      name: 'Belgium',
      code: 'BEL',
      logo: 'https://flagcdn.com/w320/be.png',
    },
    awayTeam: {
      id: 'mar',
      name: 'Morocco',
      code: 'MAR',
      logo: 'https://flagcdn.com/w320/ma.png',
    },
    homeScore: 1, // Ya tiene goles
    awayScore: 1,
    penalties: null,
  },
  {
    id: 'm-9',
    competitionId: 'wc-2026',
    date: '2026-06-10T14:00:00Z', // Fecha pasada
    stadium: 'Estadio BBVA, Monterrey',
    homeTeam: {
      id: 'ned',
      name: 'Netherlands',
      code: 'NED',
      logo: 'https://flagcdn.com/w320/nl.png',
    },
    awayTeam: {
      id: 'sen',
      name: 'Senegal',
      code: 'SEN',
      logo: 'https://flagcdn.com/w320/sn.png',
    },
    homeScore: 2,
    awayScore: 0,
    penalties: null,
  },
  {
    id: 'm-10',
    competitionId: 'wc-2026',
    date: '2026-06-30T16:00:00Z',
    stadium: 'MetLife Stadium, New Jersey',
    homeTeam: {
      id: 'cro',
      name: 'Croatia',
      code: 'CRO',
      logo: 'https://flagcdn.com/w320/hr.png',
    },
    awayTeam: {
      id: 'den',
      name: 'Denmark',
      code: 'DEN',
      logo: 'https://flagcdn.com/w320/dk.png',
    },
    homeScore: 1,
    awayScore: 1,
    penalties: { home: 4, away: 3 }, // Croacia gana en penales
  },
];
